dbt_training_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: admin
      password: admin
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10
